# STEP-5: ANOMALY DETECTION

In [1]:
import pandas as pd
import numpy as np
print("Libraries imported successfully")

Libraries imported successfully

In [2]:
df = pd.read_csv("generate_data.csv")
df['timestamp'] = pd.to_datetime(df['timestamp'])
print("Data set loaded successfully")
df.head()

Data set loaded successfully

   timestamp    room    student     appliance  energy_kwh
0 2024-01-01  Room-1  Student_A            AC       1.500
1 2024-01-01  Room-1  Student_A           Fan       0.048
2 2024-01-01  Room-1  Student_A         Light       0.010
3 2024-01-01  Room-1  Student_A        Laptop       0.056
4 2024-01-01  Room-1  Student_A  Refrigerator       0.220

In [3]:
mean_energy = df['energy_kwh'].mean()
std_energy = df['energy_kwh'].std()
print("Mean of the energy_kwh:",mean_energy)
print("STD of the energy_kwh:",std_energy)

Mean of the energy_kwh: 0.7026055107526883
STD of the energy_kwh: 0.9464031735239566

In [4]:
# We consider energy usage as anomalous if:
# - energy_kwh > mean + 2 × standard deviation

df['stat_anomaly'] = df['energy_kwh'].apply(
    lambda x: 1 if x > (mean_energy + 2 * std_energy) else 0
)

In [5]:
# If energy consumption > threshold → wastage
df['wastage_flag'] = np.where(df['energy_kwh'] > 5, 1, 0)

In [6]:
# Efficiency = usage compared to average
df['efficiency_score'] = df['energy_kwh'] / df['energy_kwh'].mean()

In [7]:
df['final_anomaly'] = (
    (df['wastage_flag'] == 1) |
    (df['stat_anomaly'] == 1) |
    (df['efficiency_score'] > 1.5)
).astype(int)

print("Final anomaly flag created using rule-based and statistical conditions.")

Final anomaly flag created using rule-based and statistical conditions.

In [8]:
anomalies_sample = df[df['final_anomaly'] == 1].head()

print("Displaying sample records identified as anomalies:")
anomalies_sample

Displaying sample records identified as anomalies:

,timestamp,room,student,appliance,energy_kwh,stat_anomaly,wastage_flag,efficiency_score,final_anomaly
0,2024-01-01,Room-1,Student_A,AC,1.500,0,0,2.134911,1
6,2024-01-01,Room-2,Student_B,AC,1.866,0,0,2.655829,1
11,2024-01-01,Room-2,Student_B,Heater,1.438,0,0,2.046668,1
12,2024-01-01,Room-3,Student_C,AC,1.565,0,0,2.227423,1
17,2024-01-01,Room-3,Student_C,Heater,2.448,0,0,3.484174,1

In [9]:
appliance_anomalies = df[df['final_anomaly'] == 1].groupby('appliance')['energy_kwh'].count()

print("Calculated number of anomalies per appliance:")
appliance_anomalies.sort_values(ascending=False)

Calculated number of anomalies per appliance:

appliance
AC        2976
Heater    2896
Name: energy_kwh, dtype: int64

In [10]:
student_anomalies = df[df['final_anomaly'] == 1].groupby('student')['energy_kwh'].count()

print("Calculated number of anomalies per student:")
student_anomalies.sort_values(ascending=False)

Calculated number of anomalies per student:

student
Student_B    1471
Student_D    1470
Student_A    1467
Student_C    1464
Name: energy_kwh, dtype: int64

In [11]:
room_anomalies = df[df['final_anomaly'] == 1].groupby('room')['energy_kwh'].count()

print("Calculated number of anomalies per room:")
room_anomalies.sort_values(ascending=False)

Calculated number of anomalies per room:

room
Room-2    1471
Room-4    1470
Room-1    1467
Room-3    1464
Name: energy_kwh, dtype: int64

In [12]:
hourly_anomalies = df[df['final_anomaly'] == 1].groupby(df['timestamp'].dt.hour)['energy_kwh'].count()

print("Calculated number of anomalies occurring at each hour of the day:")
hourly_anomalies

Calculated number of anomalies occurring at each hour of the day:

timestamp
0     245
1     244
2     244
3     241
4     246
5     244
6     245
7     246
8     245
9     244
10    242
11    245
12    242
13    245
14    243
15    244
16    243
17    243
18    246
19    246
20    245
21    248
22    248
23    248
Name: energy_kwh, dtype: int64

In [14]:
total_anomalies = df['final_anomaly'].sum()

print("STEP-5 ANOMALY DETECTION COMPLETED")
print("Total number of anomalous energy usage records detected:", total_anomalies)
print(df.columns)

STEP-5 ANOMALY DETECTION COMPLETED
Total number of anomalous energy usage records detected: 5872
Index(['timestamp', 'room', 'student', 'appliance', 'energy_kwh',
       'stat_anomaly', 'wastage_flag', 'efficiency_score', 'final_anomaly'],
      dtype='object')

## INSIGHTS FROM ANOMALY DETECTION (STEP-5):

#### 1. Night-time energy usage accounts for a significant portion of anomalies.
#### 2. AC and Heater appliances are the most frequently inefficient devices.
#### 3. Certain students consistently contribute to abnormal energy consumption.
#### 4. Specific rooms show repeated anomalous behavior, indicating appliance or usage issues.
#### 5. Rule-based and statistical methods effectively detect wastage without machine learning.
#### 6. The dataset is now fully ready for forecasting and Power BI visualization.