# STEP 2: DATA UNDERSTANDING & VALIDATION

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("generate_data.csv")
df.head()

             timestamp    room    student     appliance  energy_kwh
0  2024-01-01 00:00:00  Room-1  Student_A            AC       1.500
1  2024-01-01 00:00:00  Room-1  Student_A           Fan       0.048
2  2024-01-01 00:00:00  Room-1  Student_A         Light       0.010
3  2024-01-01 00:00:00  Room-1  Student_A        Laptop       0.056
4  2024-01-01 00:00:00  Room-1  Student_A  Refrigerator       0.220

In [7]:
df.shape

(17856, 5)

In [ ]:
df.columns

Index(['timestamp', 'room', 'student', 'appliance', 'energy_kwh'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17856 entries, 0 to 17855
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   timestamp   17856 non-null  object
 1   room        17856 non-null  object
 2   student     17856 non-null  object
 3   appliance   17856 non-null  object
 4   energy_kwh  17856 non-null  float64
dtypes: float64(1), object(4)
memory usage: 697.6+ KB

In [6]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [7]:
df["hour"] = df["timestamp"].dt.hour
df["day"] = df["timestamp"].dt.day
df["weekday"] = df["timestamp"].dt.day_name()

df.head()

   timestamp    room    student     appliance  energy_kwh  hour  day weekday
0 2024-01-01  Room-1  Student_A            AC       1.500     0    1  Monday
1 2024-01-01  Room-1  Student_A           Fan       0.048     0    1  Monday
2 2024-01-01  Room-1  Student_A         Light       0.010     0    1  Monday
3 2024-01-01  Room-1  Student_A        Laptop       0.056     0    1  Monday
4 2024-01-01  Room-1  Student_A  Refrigerator       0.220     0    1  Monday

In [8]:
df.describe()

                 timestamp    energy_kwh         hour           day
count                17856  17856.000000  17856.00000  17856.000000
mean   2024-01-16 11:30:00      0.702606     11.50000     16.000000
min    2024-01-01 00:00:00      0.006000      0.00000      1.000000
25%    2024-01-08 17:45:00      0.080000      5.75000      8.000000
50%    2024-01-16 11:30:00      0.151000     11.50000     16.000000
75%    2024-01-24 05:15:00      1.434000     17.25000     24.000000
max    2024-01-31 23:00:00     14.440000     23.00000     31.000000
std                    NaN      0.946403      6.92238      8.944522

In [9]:
df.isnull().sum()

timestamp     0
room          0
student       0
appliance     0
energy_kwh    0
hour          0
day           0
weekday       0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [24]:
print("Appliance usage by high to low")
appliance_usage = df.groupby("appliance")["energy_kwh"].mean().sort_values(ascending=False)
appliance_usage

Appliance usage by high to low

appliance
Heater          2.020214
AC              1.736278
Refrigerator    0.203079
Fan             0.103997
Laptop          0.101804
Light           0.050260
Name: energy_kwh, dtype: float64

In [23]:
print("Student consumption by high to low")
student_usage = df.groupby("student")["energy_kwh"].mean().sort_values(ascending=False)
student_usage

Student consumption by high to low

student
Student_D    0.710883
Student_A    0.703168
Student_C    0.698846
Student_B    0.697524
Name: energy_kwh, dtype: float64

In [22]:
print("Room consumption by high to low")
room_usage = df.groupby("room")["energy_kwh"].mean().sort_values(ascending=False)
room_usage

Room consumption by high to low

room
Room-4    0.710883
Room-1    0.703168
Room-3    0.698846
Room-2    0.697524
Name: energy_kwh, dtype: float64

In [27]:
print("Time Wasteage")
avg_energy = df["energy_kwh"].mean()

wastage_df = df[
    ((df["hour"] >= 22) | (df["hour"] <= 5)) &
    (df["appliance"].isin(["AC", "Heater"])) &
    (df["energy_kwh"] > avg_energy)
]

wastage_df.head()

Time Wasteage

    timestamp    room    student appliance  energy_kwh  hour  day weekday
0  2024-01-01  Room-1  Student_A        AC       1.500     0    1  Monday
5  2024-01-01  Room-1  Student_A    Heater       1.031     0    1  Monday
6  2024-01-01  Room-2  Student_B        AC       1.866     0    1  Monday
11 2024-01-01  Room-2  Student_B    Heater       1.438     0    1  Monday
12 2024-01-01  Room-3  Student_C        AC       1.565     0    1  Monday

In [29]:
print("Wastage Records")
len(wastage_df)

Wastage Records

1984

In [31]:
df.to_csv("clean_energy_data.csv", index=False)
wastage_df.to_csv("wastage_records.csv", index=False)
print("DATA UNDERSTANDING & VALIDATION COMPLETED")

DATA UNDERSTANDING & VALIDATION COMPLETED